# Generated by Django 3.0.5 on 2020-05-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('doctor', models.CharField(max_length=200)),
                ('patient', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='1', max_length=20)),
                ('age', models.IntegerField(blank=True)),
                ('address', models.CharField(max_length=300)),
                ('department', models.CharField(choices=[('Neurologist', 'Neurologist'), ('Psychiatrist', 'Psychiatrist'), ('Anesthesiologist', 'Anesthesiologist'), ('Dermatologist', 'Dermatologist'), ('Cardiologist', 'Cardiologist'), ('Orthopedist', 'Orthopedist')], default='1', max_length=30)),
                ('salary', models.IntegerField(blank=True)),
                ('attendance', models.IntegerField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active')], default='1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='1', max_length=20)),
                ('age', models.IntegerField(blank=True)),
                ('address', models.CharField(max_length=300)),
                ('outstanding', models.IntegerField(blank=True)),
                ('paid', models.IntegerField(blank=True)),
                ('blood_groop', models.CharField(choices=[('A+', 'A+ Type'), ('B+', 'B+ Type'), ('AB+', 'AB+ Type'), ('O+', 'O+ Type'), ('A-', 'A- Type'), ('B-', 'B- Type'), ('AB-', 'AB- Type'), ('O-', 'O- Type')], default='1', max_length=40)),
                ('med_reps', models.FileField(blank=True, upload_to='')),
                ('case_paper', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('symptoms', models.CharField(max_length=100)),
                ('prescription', models.CharField(max_length=300)),
                ('patient', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('register_as', models.CharField(choices=[('1', 'Patient'), ('2', 'Doctor'), ('3', 'HR'), ('4', 'Receptionist')], default='1', max_length=20)),
            ],
        ),
    ]
